api/urls.py
from django.urls import path

from .views import UserListAPIView, UserDetailAPIView, PostDetailAPIView

app_name = 'api'

urlpatterns = [
    path('', UserListAPIView.as_view(), name='list'),
    path('user/<slug:user_slug>', UserDetailAPIView.as_view(), name='detail'),
    path('post/<slug:slug>/', PostDetailAPIView.as_view(), name='post_detail')
]

friends/urls.py
from django.urls import path

from .views import action, friends, requests, subscriptions

app_name = 'friend'

urlpatterns = [
    path('', friends, name='friends'),
    path('requests/', requests, name='requests'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('action/<str:redirect_app_name>', action, name='action')
]

posts/urls.py
from django.urls import path

from .views import create, edit, delete, detail

app_name = 'posts'

urlpatterns = [
    path('create/', create, name='create'),
    path('edit/<slug:slug>/', edit, name='edit'),
    path('delete/<slug:slug>/', delete, name='delete'),
    path('detail/<slug:user_slug>/title/<slug:slug>/', detail, name='detail')
]

profiles/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetCompleteView, LogoutView
from django.urls import path

from .views import ResetPassword, ConfirmResetPassword
from .views import list, detail, edit
from .views import registration, login, change_password

app_name = 'profile'

urlpatterns = [
    path('', detail, name='me'),
    path('user/<slug:user_slug>/', detail, name='detail'),
    path('users/', list, name='list'),
    path('change/', edit, name='edit'),
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', change_password, name='change_password'),

    path('password-reset/', ResetPassword.as_view(), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', ConfirmResetPassword.as_view(), name='password_reset_confirm'),
    path('password-reset-compile/', PasswordResetCompleteView.as_view(), name='password_reset_complete')

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('post/', include('posts.urls', namespace='post')),
    path('friend/', include('friends.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('news.urls', namespace='news')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.apps import apps
from django.contrib.auth.models import PermissionsMixin, BaseUserManager, AbstractBaseUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.text import gettext_lazy as _
from django.urls import reverse_lazy


class UserManager(BaseUserManager):
    def _create_user(self, email, username, password, **extra_fields):
        if not email and not username:
            raise ValueError('The given email and username must be set')
        email = self.normalize_email(email)
        GlobaslUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobaslUserModel.normalize_username(username)
        extra_fields.setdefault('user_slug', slugify(username))
        user = self.model(email=email, username=username, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_active') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, username, password, **extra_fields)


class AbstractUser(AbstractBaseUser, PermissionsMixin):
    """ Model User  """
    username_validator = UnicodeUsernameValidator()

    email = models.EmailField(_('email'), max_length=71, unique=True)
    username = models.CharField(_('username'), max_length=150, unique=True, validators=[username_validator])
    user_slug = models.SlugField(_('user slug'), max_length=150, unique=True)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    image = models.ImageField(_('image'), upload_to='profiles/%Y/%m', blank=True)
    date_of_birth = models.DateField(_('date of birth'), blank=True, null=True)
    city = models.CharField(_('city'), max_length=250, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    date_joined = models.DateTimeField(_('data joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_information(self):
        return {'id': self.id, 'first_name': self.first_name, 'last_name': self.last_name, 'image': self.image,
                'date_of_birth': self.date_of_birth, 'city': self.city}

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}' if self.first_name and self.last_name else self.username

    def get_short_name(self):
        return self.first_name if self.first_name else self.username

    def email_user(self, subject, message, from_emai=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['first_name', 'username']
        abstract = True


class User(AbstractUser):

    def get_absolute_url(self):
        return reverse_lazy('profile:detail', args=[self.user_slug])

    def get_api_url(self):
        return reverse_lazy('api:detail', args=[self.user_slug])

    def __str__(self):
        return self.username

    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.utils.text import gettext_lazy as _

from .models import User


class UserReistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']


class UserLoginForm(forms.Form):
    login = forms.CharField(label=_('login'), widget=forms.TextInput(attrs={"autofocus": True}))
    password = forms.CharField(label=_('password'), widget=forms.PasswordInput())


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'image', 'date_of_birth', 'city']

profiles/views.py
from django.conf import settings
from django.contrib.auth import authenticate, update_session_auth_hash, login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.db.models import Q, Case, Count, When
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods

from posts.models import Post
from .forms import UserReistrationForm, UserLoginForm, ProfileChangeForm
from .models import User
from .services import objects_page, search_user, search_post, set_action_user


@require_http_methods(['GET', 'POST'])
def registration(request):
    if request.method == 'POST':
        form = UserReistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = User.objects.create_user(email, username, password)

    if request.method == 'GET':
        form = UserReistrationForm()
    return render(request, 'profiles/registration.html', {'form': form})


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['login'], password=form.cleaned_data['password'])
            if user:
                auth_login(request, user)
                return redirect('profile:me')
            form.add_error('__all__', 'Login or password entered incorrectly!')

    if request.method == 'GET':
        form = UserLoginForm()
    return render(request, 'profiles/login.html', {'form': form})


@login_required
@require_http_methods(['GET', 'POST'])
def list(request):
    object_list = User.objects.annotate(
        is_request_user=Count(Case(When(friend_requests__user=request.user, friend_requests__friends=False, then=1))),
        is_subscribed=Count(Case(When(subscriptions__subscription=request.user, subscriptions__friends=False, then=1))),
        is_friend=Count(Case(When(Q(friend_requests__user=request.user, friend_requests__friends=True) |
                                  Q(subscriptions__subscription=request.user, subscriptions__friends=True), then=1))),
    ).exclude(username=request.user.username)
    if request.GET.get('search'):
        object_list = search_user(object_list, request.GET.get('search'))
    object_list = objects_page(object_list, settings.TOTAL_USER_PAGE, request.GET.get('page'))
    object_list = set_action_user(object_list)
    context = {'section': 'users', 'object_list': object_list}
    return render(request, 'profiles/list.html', context=context)


@login_required
@require_http_methods(['GET'])
def detail(request, user_slug=None):
    if user_slug:
        if request.user.user_slug == user_slug:
            return redirect('profile:me')
        user = get_object_or_404(User, user_slug=user_slug)
        object_list = Post.objects.filter(user=user)
    else:
        user = request.user
        object_list = Post.objects.filter(user=request.user)
    object_list = search_post(object_list, request.GET.get('search')) if request.GET.get('search') else object_list
    object_list = objects_page(object_list, settings.TOTAL_POST_PAGE, request.GET.get('page'))
    return render(request, 'profiles/detail.html', {'section': 'profile', 'user': user, 'object_list': object_list})


@login_required
@require_http_methods(['GET', 'POST'])
def edit(request):
    if request.method == 'POST':
        form = ProfileChangeForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('profile:me')
    if request.method == 'GET':
        form = ProfileChangeForm(instance=request.user)
    return render(request, 'profiles/edit.html', {'form': form})


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('profile:me')
    if request.method == 'GET':
        form = PasswordChangeForm(request.user)
    return render(request, 'profiles/change_password.html', {'form': form})


class ResetPassword(PasswordResetView):
    success_url = reverse_lazy('profile:password_reset_done')


class ConfirmResetPassword(PasswordResetConfirmView):
    success_url = reverse_lazy('profile:password_reset_compile')

profiles/templates/profiles/change.html
{% extends 'base.html' %}

{% block title %} Change | {{ request.user.get_full_name }} {% endblock %}


{% block content %}
<div class="profile-change-container">
    <h2 class="title-center">Change Profile</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-confirm">CHANGE</button>
    </form>
</div>


{% endblock %}

profiles/templates/profiles/change_password.html
{% extends 'base.html' %}


{% block title %} Change password {% endblock %}

{% block content %}
<div class="profile-change-container">
    <h3 class="title-center">Change password</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-confirm">CHANGE</button>
    </form>
</div>

{% endblock %}

profiles/templates/profiles/detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %} profile | {{ request.user.get_full_name }} {% endblock %}


{% block content %}

<div class="profile-container">
    <div class="profile-image">
        {% if user.image %}
        <img class="profile-image-show" src="{% thumbnail user.image 300x300 %}">
        {% else %}
        <img class="profile-image-show" src="{% static 'image/no_image.jpg' %}" alt="">
        {% endif %}
    </div>
    <div class="profile-information">
        <div><b>Email: </b>{{ user.email }}</div>
        <div><b>Username: </b>{{ user.username }}</div>
        <div><b>First name: </b>{%if user.first_name%}{{user.first_name}}{%else%}Not filled{%endif%}</div>
        <div><b>Last name: </b>{%if user.last_name%}{{user.last_name}}{%else%}Not filled{%endif%}</div>
        <div><b>Date: </b>{%if user.date_of_birth%}{{user.date_of_birth}}{%else%}Not filled{%endif%}</div>
        <div><b>City: </b>{%if user.city%}{{user.city}}{%else%}Not filled{%endif%}</div>
        <hr/>
        {% if request.user == user %}
        <div><a class="nav-link" href="{% url 'profile:edit' %}"> Edit </a></div>
        {% else %}
        <div class="title-right"><a class="nav-link" href="#"> Chat </a></div>
        {% endif %}
    </div>
    <div class="profile-posts">
        <h2 class="title-center"> --- Posts --- </h2>
        {% if request.user == user %}
        <div class="block-right"><a class="nav-link" href="{% url 'post:create' %}">Create post</a></div>
        {% endif %}
        <div class="search-container">
            {% include 'includes/search.html' %}
        </div>
        {% for obj in object_list %}
        <div class="post">
            <a class="nav-link" href="{{ obj.get_absolute_url }}">{{ obj.title }}</a><br/>
            created: {{ obj.created|date:"m-d-Y H:i:s" }}
            <br>
            {% if request.user == user %}
            action: <a class="nav-link" style="font-size: 1rem" href="{% url 'posts:edit' obj.slug %}">Edit</a> |
            <a class="nav-link" style="font-size: 1rem" href="{% url 'posts:delete' obj.slug %}">Delete</a>
            {% endif %}
            <hr/>
        </div>
        {% empty %}
        <div class="title-center"> Posts not found </div>
        {% endfor %}
        {% include 'includes/pagination.html' %}
    </div>
</div>


{% endblock %}

profiles/templates/profiles/edit.html
{% extends 'base.html' %}

{% block title %} Edit | {{ request.user.get_full_name }} {% endblock %}


{% block content %}
<div class="profile-change-container">
    <h2 class="title-center">Edit Profile</h2>
    <div class="title-right">
        <a class="nav-button-confirm" href="{% url 'profile:change_password' %}">Change password</a>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-confirm">CHANGE</button>
    </form>
</div>


{% endblock %}

profiles/templates/profiles/list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %} Users {% endblock %}

{% block content %}

<h3 class="title-center">Users</h3>
<hr class="title-center" width="50%"/>
<div class="search-container">
    {% include 'includes/search.html' %}
</div>
{% for user in object_list %}
<div class="users">
    <div class="user-image">
        <a href="{{ user.get_absolute_url }}">
            {% if user.image %}
            <img class="user-image-show" src="{% thumbnail user.image 170x170 %}" alt=""/>
            {% else %}
            <img class="user-image-show" src="{% static 'image/no_image.jpg' %}" alt="">
            {% endif %}
        </a>
    </div>
    <div class="user-information">
        <div>
            <div>
                <a class="nav-link" href="{{ user.get_absolute_url }}">{{ user.get_full_name }}</a>
            </div>
            <div>
                <form action="{% url 'friend:action' 'profile' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="user" value="{{ user.id }}">
                    <input type="hidden" name="action" value="{{ user.action }}">

                    <button class="button-confirm" type="submit">
                        {{ user.action }}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% include 'includes/pagination.html' %}

{% endblock %}

profiles/templates/profiles/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content_not_user %}
<form class="registartion-form" action="" method="POST">
    <h3 class="registration-title">LOGIN</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <a class="nav-link" style="font-size: 1rem" href="{% url 'profile:password_reset' %}">
        Forgot your password?
    </a><br/>
    <button class="button-confirm" style="margin-top: 1rem" type="submit">LOGIN</button>
</form>
{% endblock %}

profiles/templates/profiles/registration.html
{% extends 'base.html' %}

{% block title %} Registration {% endblock %}

{% block content_not_user %}
<form class="registartion-form" action="" method="POST">
    <h3 class="title-center">REGISTRATION</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button-confirm" type="submit">REGISTRATION</button>
</form>

{% endblock %}