api/urls.py
from django.urls import path

from .views import UserListAPIView, UserDetailAPIView, PostDetailAPIView

app_name = 'api'

urlpatterns = [
    path('', UserListAPIView.as_view(), name='list'),
    path('user/<slug:user_slug>', UserDetailAPIView.as_view(), name='detail'),
    path('post/<slug:slug>/', PostDetailAPIView.as_view(), name='post_detail')
]

friends/urls.py
from django.urls import path

from .views import action, friends, requests, subscriptions

app_name = 'friend'

urlpatterns = [
    path('', friends, name='friends'),
    path('requests/', requests, name='requests'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('action/<str:redirect_app_name>', action, name='action')
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('post/', include('posts.urls', namespace='post')),
    path('friend/', include('friends.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('news.urls', namespace='news')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friends/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

from profiles.models import User
from news.models import Action


class Friend(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions')
    subscription = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend_requests')
    friends = models.BooleanField(default=False, help_text='Friend request confirmation')
    black_list = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} {self.subscription}'

    class Meta:
        unique_together = ('user', 'subscription')
        verbose_name = 'firend'
        verbose_name_plural = 'friends'


@receiver(post_save, sender=Friend)
def create_action(sender, instance, created, **kwargs):
    if created:
        Action.objects.create(user=instance.user, verb=settings.ACTION_VERBS['subscribe'],
                              target_object=instance.subscription)
    if not created and instance.friends:
        Action.objects.create(user=instance.subscription, verb=settings.ACTION_VERBS['friend'],
                              target_object=instance.user)
        Action.objects.create(user=instance.user, verb=settings.ACTION_VERBS['friend'],
                              target_object=instance.subscription)

friends/forms.py
from django import forms
from django.conf import settings

from profiles.models import User


class FriendForm(forms.Form):
    ACTION_CHOICES = (
        (settings.ACTIONS_USER['subscribe'], settings.ACTIONS_USER['subscribe']),
        (settings.ACTIONS_USER['cancel'], settings.ACTIONS_USER['cancel']),
        (settings.ACTIONS_USER['confirm'], settings.ACTIONS_USER['confirm']),
        (settings.ACTIONS_USER['remove'], settings.ACTIONS_USER['remove']),
        (settings.ACTIONS_USER['black_list'], settings.ACTIONS_USER['black_list'])
    )
    user = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())
    action = forms.ChoiceField(choices=ACTION_CHOICES, widget=forms.HiddenInput())

friends/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from profiles.models import User
from .forms import FriendForm
from .services import action_friend, get_context


@login_required
def action(request, redirect_app_name):
    form = FriendForm(request.POST)
    print(request.POST)
    if form.is_valid():
        action_friend(request.user, form.cleaned_data['user'])
    if redirect_app_name == 'friend':
        return redirect('friend:friends')
    return redirect('profile:list')


@login_required
def friends(request):
    object_list = User.objects.filter(
        Q(friend_requests__user=request.user, friend_requests__friends=True) |
        Q(subscriptions__subscription=request.user, subscriptions__friends=True)
    ).exclude(username=request.user.username).distinct()
    context = get_context(request, object_list, 'remove')
    return render(request, 'friends/list.html', context=context)


def requests(request):
    object_list = User.objects.filter(
        subscriptions__subscription=request.user, subscriptions__friends=False
    ).exclude(username=request.user.username).distinct()
    context = get_context(request, object_list, 'confirm')
    return render(request, 'friends/list.html', context=context)


@login_required
def subscriptions(request):
    object_list = User.objects.filter(
        friend_requests__user=request.user, friend_requests__friends=False
    ).exclude(username=request.user.username).distinct()
    context = get_context(request, object_list, 'cancel')
    return render(request, 'friends/list.html', context=context)

friends/templates/friends/list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %} Friends {% endblock %}

{% block content %}
<div class="frind-header-container">
    <div class="friend-header-item friend-header-confirm">
        <a class="nav-link" style="font-size: 1.2rem" href="{% url 'friend:friends' %}">
            Friends
        </a>
    </div>
    <div class="friend-header-item friend-header-request">
        <a class="nav-link" style="font-size: 1.2rem" href="{% url 'friend:requests' %}">
            Friend requests
        </a>
    </div>
    <div class="friend-header-item friend-header-subscribers">
        <a class="nav-link" style="font-size: 1.2rem" href="{% url 'friend:subscriptions' %}">
            Subscriptions
        </a>
    </div>
</div>
<div class="search-container" style="margin-top: 1rem">
    {% include 'includes/search.html' %}
</div>
<div class="friend-users">
    {% for user in object_list %}
    <div class="users">
        <div class="user-image">
            <a href="{{ user.get_absolute_url }}">
                {% if user.image %}
                <img class="user-image-show" src="{% thumbnail user.image 170x170 %}" alt=""/>
                {% else %}
                <img class="user-image-show" src="{% static 'image/no_image.jpg' %}" alt="">
                {% endif %}
            </a>
        </div>
        <div class="user-information">
            <div>
                <div>
                    <a class="nav-link" href="{{ user.get_absolute_url }}">{{ user.get_full_name }}</a>
                </div>
                <div>
                    <form action="{% url 'friend:action' 'friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="user" value="{{ user.id }}">
                        <input type="hidden" name="action" value="{{ action }}">
                        <button class="button-confirm" type="submit">{{ action }}</button>
                        <a class="nav-button-confirm" href="{% url 'chat:detail' user.username %}">Chat</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% include 'includes/pagination.html' %}

{% endblock %}